import type { Recommendation } from '../types';

const APP_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://myapp.com';

const frameUrlFor = (id: string) => `${APP_BASE_URL}/api/frame/${id}`;

export const seedRecommendations: Recommendation[] = [
  {
    id: '1',
    curatorAddress: '0x1234567890123456789012345678901234567890',
    musicUrl: 'https://music.youtube.com/watch?v=dQw4w9WgXcQ',
    songTitle: 'Midnight Drive',
    artist: 'Synthwave Dreams',
    album: 'Neon Nights',
    review: 'Perfect late-night coding soundtrack. The synth layers build gradually and keep you in flow state without being distracting.',
    genre: 'Electronic',
    moods: ['Chill', 'Focus'],
    tipCount: 150,
    timestamp: Date.now() - 3600000,
    frameUrl: frameUrlFor('1'),
  },
  {
    id: '2',
    curatorAddress: '0xabcdefabcdefabcdefabcdefabcdefabcdefabcd',
    musicUrl: 'https://open.spotify.com/track/example',
    songTitle: 'Summer Haze',
    artist: 'The Velvet Waves',
    album: 'Cosmic Bloom',
    review: "Hidden gem from 2019. If you loved Tame Impala's Currents, this will hit the same spot. Psychedelic but groovy.",
    genre: 'Indie',
    moods: ['Energetic', 'Happy'],
    tipCount: 75,
    timestamp: Date.now() - 7200000,
    frameUrl: frameUrlFor('2'),
  },
  {
    id: '3',
    curatorAddress: '0x9876543210987654321098765432109876543210',
    musicUrl: 'https://soundcloud.com/artist/track',
    songTitle: 'Reflections',
    artist: 'Miles Azure',
    album: 'Blue Notes',
    review: 'Raw emotion. This track saved me during a tough week. Simple piano, powerful lyrics. Listen with headphones.',
    genre: 'Jazz',
    moods: ['Melancholic'],
    tipCount: 200,
    timestamp: Date.now() - 10800000,
    frameUrl: frameUrlFor('3'),
  },
  {
    id: '4',
    curatorAddress: '0x5555555555555555555555555555555555555555',
    musicUrl: 'https://music.apple.com/us/album/example',
    songTitle: 'Golden Hour',
    artist: 'Luna Bay',
    album: 'Sunset Sessions',
    review: 'Discovered this at a rooftop party in Brooklyn. Instant summer anthem. Makes you want to dance under the stars.',
    genre: 'Pop',
    moods: ['Happy', 'Energetic'],
    tipCount: 125,
    timestamp: Date.now() - 14400000,
    frameUrl: frameUrlFor('4'),
  },
  {
    id: '5',
    curatorAddress: '0x7777777777777777777777777777777777777777',
    musicUrl: 'https://open.spotify.com/track/example2',
    songTitle: 'Beast Mode',
    artist: 'DJ Apex',
    album: 'Grind Time',
    review: 'The bass line in this is absolutely filthy. Perfect for morning workouts when you need that extra push.',
    genre: 'Hip-Hop',
    moods: ['Energetic'],
    tipCount: 90,
    timestamp: Date.now() - 18000000,
    frameUrl: frameUrlFor('5'),
  },
];
